/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddEditModal: typeof import('./../src/components/Tbl/AddEditModal.vue')['default']
    AddQuery: typeof import('./../src/components/Tbl/AddQuery.vue')['default']
    Chart: typeof import('./../src/components/Chart/index.vue')['default']
    ColumnFilter: typeof import('./../src/components/ColumnFilter.vue')['default']
    DataTable: typeof import('./../src/components/DataTable/index.vue')['default']
    DictTag: typeof import('./../src/components/DictTag.vue')['default']
    DtaTbl: typeof import('./../src/components/DtaTbl/index.vue')['default']
    EditModal: typeof import('./../src/components/Tbl/EditModal.vue')['default']
    EditModel: typeof import('./../src/components/Tbl/EditModel.vue')['default']
    ElSvgIcon: typeof import('./../src/components/ElSvgIcon.vue')['default']
    InnerLink: typeof import('./../src/components/InnerLink/index.vue')['default']
    JsonInput: typeof import('./../src/components/JsonInput.vue')['default']
    MyTable: typeof import('./../src/components/MyTable/index.vue')['default']
    Pagination: typeof import('./../src/components/Pagination/index.vue')['default']
    ParentView: typeof import('./../src/components/ParentView/index.vue')['default']
    RightToolbar: typeof import('./../src/components/RightToolbar/index.vue')['default']
    RightToolBar: typeof import('./../src/components/RightToolBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/icons/SvgIcon.vue')['default']
    Tbl: typeof import('./../src/components/Tbl/index.vue')['default']
    TestUnit: typeof import('./../src/components/TestUnit.vue')['default']
  }
}
