server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/east_wind?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: 996forCredit
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    password: 123456
mybatis:
  #  指定mapper映射文件的位置
  mapper-locations: "classpath:mapper/*Mapper.xml"
  #   配置mybatis的别名
  type-aliases-package: com.ew.entity
#  todo 不起作用
#  type-handlers-package: com.ew.handlers

logging:
  level:
    #    写自己程序的包 日志级别是debug，这样控制台就可打印信息
    com.ew: debug